DROP DATABASE IF EXISTS EUROLIGA;

CREATE DATABASE EUROLIGA;

USE EUROLIGA;

CREATE TABLE EQUIPO (
	NOMBRE VARCHAR(50) PRIMARY KEY,
	CIUDAD VARCHAR(50) NOT NULL,
	PRESUPUESTO INTEGER(5) NOT NULL
);

CREATE TABLE JUGADOR(
    DORSAL INTEGER(5) UNSIGNED,
    NOMBRE VARCHAR(50) NOT NULL,
    SALARIO INTEGER(5) NOT NULL,
    NOM_EQUIPO VARCHAR(50) NOT NULL,
	FOREIGN KEY (NOM_EQUIPO) REFERENCES EQUIPO (NOMBRE),
    PRIMARY KEY (DORSAL, NOM_EQUIPO)
);

INSERT INTO EQUIPO (
	NOMBRE,
    CIUDAD,
	PRESUPUESTO
)
VALUES
	("Equipo1", "Ciudad1", 70000),
	("Equipo2", "Ciudad2", 10000)
;

INSERT INTO JUGADOR (
    DORSAL,
	NOMBRE,
    SALARIO,
	NOM_EQUIPO
)
VALUES
	(1, "Jugador1", 1000, "Equipo2"),
    (2, "Jugador2", 2000, "Equipo2"),
    (3, "Jugador3", 3000, "Equipo2"),
    (4, "Jugador4", 4000, "Equipo1"),
    (5, "Jugador5", 5000, "Equipo1"),
    (6, "Jugador6", 6000, "Equipo1")
;